### PR TITLE
some housekeeping

### PR DESCRIPTION
**Pull request by joechrz**
a little bit of housekeeping to get the grid ready for our implementation

* remove babel (because node does arrow funcs now)
* fix 2 typescript compilation errors
* remove the evil `text-transform: uppercase` thing that had me so confused
* remove a few default styles that set background-colors (because working around them was kinda nasty)
* upgrade to support node 10 and npm 6 (npm 6 is what changed the package-lock.json file so significantly)

### CODE REVIEW

**Comment by joechrz** [comment]
wait don't merge package-lock is borked

**Comment by joechrz** [comment]
ok... @scamden thoughts on this?

i can revert the style changes if it causes too much hassle on your end.

**Comment by joechrz** [comment]
> I think we still need babel for ie11 over here unfortunately

I didn't actually see it used anywhere besides the `tools/srcServer` file so it seemed safe to delete.  TS should compile down to ES2015 and I thought the grid natively worked in IE11 after that.... happy to put it back if it's actually needed just trying to understand the build process a little more.

> maybe if we are going to remove the color styles we can move them to another file grid-colors.scss? that way you can get the default color styling if you want it

Yeah... I got lazy :) I can put the styles back in there now and if I have some time this week I can work more on separating visual vs. layout.

**Comment by scamden** [comment]
sounds good :) but obviously feel free to leave out the text transform :P

**Pull request closed without merging**
